# permissions for end users to edit pizzaorders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pizzaorder-editor-role
rules:
- apiGroups:
  - store.example.zoncoen.net
  resources:
  - pizzaorders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - store.example.zoncoen.net
  resources:
  - pizzaorders/status
  verbs:
  - get
